# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ecb6495596ea5c203db02705f1efc9d6a053bc9ecd872440158064e3636f86b902a28d9cfbffa6fc19ef4d4b3acb5b330fd34d618f9bbd2b30302b8356c8f0a

test:
  secret_key_base: b90bc85c0423a62af64fc427fbb50855f4d3973492a93b1da3566797b67a855e7083c1ce530ce05b91a1cf0ff8720cdec7bc81986767e6d969a9a2d73d70d34f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
